# Copyright 2016-2022 NXP
# SPDX-License-Identifier: MIT
g_dctENG = {
    "数据集化简分割工具" : "subdataset tool",
    "子块数据集配置" : "sub patch config",
    "合并至少几个邻近物体" : "Min nearby objects to merge",
    "生成数量" : "Output cnt",
    "子块 H" : "Patch H",
    "子块 W" : "Patch W",
    "单物体面积占比范围" : "Boxes area ratio range",
    "物体区域最小占比" : "Min box area ratio",
    "允许更密集" : "Allow denser",
    "只使用长宽比符合约束的物体" : "Only use objects that satisfy H:W constraints",
    "源数据集选择" : "Select input dataset",
    "子集" : "usage",
    "选择目录...": "Folder...",
    "类型": "Type",
    "装载": "Load",
    "自动装载": "Auto load",
    "随机显示": "Show random",
    "导出标注": "Export labels",
    "边框高/宽的范围": "min,max H:W of bbox",
    "每张图中边框个数的范围": "min,max bboxes per image",
    "只读取符合约束的图": "Only read images that satisfy constraints",
    "生成子块数据集": "Generate sub-patch dataset",
    "中止": "Abort",
    "输出目录有时间戳": "Timestamp in out folder",
    "验证子块数据集与工具": "Validation and tools",
    "多框": "N-box",
    "单框": "1-box",
    "原图": "Source",
    "刷新标注": "Refresh labels",
    "反选": "Invert",
    "类别筛选": "Category filter",
    "全选": "Sel All",
    "删除未选中的类别": "Del non-checked",
    "导出数据集格式": "Export format",
    "导出": "Export",
    "文件": "File",
    "调试": "Debug",
    "工具": "Tools",
    "只在当前图像上生成多框数据集" : "Generate N-box sub dataset for current image",
    "显示指定的图像..." : "Show specified image number...",
    "删除未选中的标签" : "Delete non-checked tags",
    "锚框工具" : "Anchor-box tool",
    "保存配置" : "Save config",
    "配置另存为..." : "Save config as...",
    "打开配置" : "Open config",
    "自动打开上次配置" : "Auto open last config",
    '在当前子集和约束条件下，%s中未找到符合要求的%s格式数据集！' : 'In current subset and constraints, we didn\'t found dataset in %s to be parsed as %s!',
    "数据集化简分割工具 - 已加载%s类型的数据集于：%s" : "subdataset tool - Loaded %s format dataset from folder %s",
    '数据集%s (%s)读取成功!' : 'Dataset%s (%s) successfully loaded!',
    '数据集读取中...' : 'Loading dataset...',
    '未找到图片' : 'Image not found',
    '未找到制作的数据集' : 'Generated dataset not found',
    '制作了%d/%d张图片于%s' : 'Generated %d/%d images in %s',
    '制作中, 图片%d' : 'Making sub dataset, image %d',
    '不能制作 - 源数据集路径不能与输出路径相同！' : 'Cannot make dataset - dataset source folder must NOT be the same as dest folder!',
    '生成结果统计' : 'Generating result statistics',
    '没有生成任何数据' : 'No data is generated!',
    '选取文件夹' : 'Select folder',
    '已保存到%s' : 'Saved to %s',
    '正在保存' : 'Saving',
    '随机显示编号%d, 图片%s' : 'Show random image index %d, name %s',
    '转换完成' : 'Conversion complete',
    '导出中...' : 'Exporting',
    '正在清洗%s %s' : 'Cleaning %s %s',
    '设置当前图片索引' : 'Specify number for current image',
    'Input number：' : 'Input number：',
    '无效的图片号%d' : 'Invalid image number %d',
    '显示指定编号%d, 图片%s' : 'Show specified image number %d : %s',
    '保存UI配置' : 'Save UI configuration',
    '读取UI配置' : 'Load UI configuration'    
}

g_dctCHS = {
    "数据集化简分割工具" : "数据集化简分割工具",
    "子块数据集配置" : "子块数据集配置",
    "合并至少几个邻近物体" : "合并至少几个邻近物体",
    "生成数量" : "生成数量",
    "子块 H" : "子块 H",
    "子块 W" : "子块 W",
    "单物体面积占比范围" : "单物体面积占比范围",
    "物体区域最小占比" : "物体区域最小占比",
    "允许更密集" : "允许更密集",
    "只使用长宽比符合约束的物体" : "只使用长宽比符合约束的物体",
    "源数据集选择" : "源数据集选择",
    "子集" : "子集",
    "选择目录..." : "选择目录...",
    "类型" : "类型",
    "装载" : "装载",
    "自动装载" : "自动装载",
    "随机显示" : "随机显示",
    "导出标注" : "导出标注",
    "边框高/宽的范围" : "边框高/宽的范围",
    "每张图中边框个数的范围" : "每张图中边框个数的范围",
    "只读取符合约束的图" : "只读取符合约束的图",
    "生成子块数据集" : "生成子块数据集",
    "单框" : "单框",
    "多框" : "多框",
    "中止" : "中止",
    "输出目录有时间戳" : "输出目录有时间戳",
    "验证子块数据集与工具" : "验证子块数据集与工具",
    "原图" : "原图",
    "刷新标注" : "刷新标注",
    "反选" : "反选",
    "类别筛选" : "类别筛选",
    "全选" : "全选",
    "删除未选中的类别" : "删除未选中的类别",
    "导出数据集格式" : "导出数据集格式",
    "导出" : "导出",
    "文件" : "文件",
    "调试" : "调试",
    "工具" : "工具",
    "只在当前图像上生成多框数据集" : "只在当前图像上生成多框数据集",
    "显示指定的图像..." : "显示指定的图像...",
    "删除未选中的标签" : "删除未选中的标签",
    "锚框工具" : "锚框工具",
    "保存配置" : "保存配置",
    "配置另存为..." : "配置另存为...",
    "打开配置" : "打开配置",
    "自动打开上次配置" : "自动打开上次配置",
    '在当前子集和约束条件下，%s中未找到符合要求的%s格式数据集！' : '在当前子集和约束条件下，%s中未找到符合要求的%s格式数据集！',
    '数据集化简分割工具 - 已加载%s类型的数据集于：%s' : "数据集化简分割工具 - 已加载%s类型的数据集于：%s",
    '数据集%s (%s)读取成功!' : '数据集%s (%s)读取成功!',
    '数据集读取中...' : '数据集读取中...',
    '未找到图片' : '未找到图片',
    '制作了%d/%d张图片于%s' : '制作了%d/%d张图片于%s',
    '制作中, 图片%d' : '制作中, 图片%d',
    '不能制作 - 源数据集路径不能与输出路径相同！' : '不能制作 - 源数据集路径不能与输出路径相同！',
    '生成结果统计' : '生成结果统计',
    '没有生成任何数据' : '没有生成任何数据',
    '选取文件夹' : '选取文件夹',
    '已保存到%s' : '已保存到%s',
    '正在保存' : '正在保存',
    '随机显示编号%d, 图片%s' : '随机显示编号%d, 图片%s',
    '转换完成' : '转换完成',
    '导出中...' : '导出中...',
    '正在清洗%s %s' : '正在清洗%s %s',
    '设置当前图片索引' : '设置当前图片索引',
    '请输入索引：' : '请输入索引：',
    '无效的图片号%d' : '无效的图片号%d',
    '显示指定编号%d, 图片%s' : '显示指定编号%d, 图片%s',
    '保存UI配置' : '保存UI配置',
    '读取UI配置' : '读取UI配置'
    
}

g_dctLang = {
    'ENG' : g_dctENG,
    'CHS' : g_dctCHS
}