
g_dctENG = {
    "数据集化简分割工具" : "subdataset tool",
    "子块数据集配置" : "sub patch config",
    "合并至少几个邻近物体" : "Min nearby objects to merge",
    "生成数量" : "Output cnt",
    "子块 H" : "Patch H",
    "子块 W" : "Patch W",
    "单物体面积占比范围" : "Boxes area ratio range",
    "物体区域最小占比" : "Min box area ratio",
    "允许更密集" : "Allow denser",
    "只使用长宽比符合约束的物体" : "Only use objects that satisfy H:W constraints",
    "源数据集选择" : "Select input dataset",
    "子集" : "usage",
    "选择目录...": "Folder...",
    "类型": "Type",
    "装载": "Load",
    "自动装载": "Auto load",
    "随机显示": "Show random",
    "导出标注": "Export labels",
    "边框高/宽的范围": "min,max H:W of bbox",
    "每张图中边框个数的范围": "min,max bboxes per image",
    "只读取符合约束的图": "Only read images that satisfy constraints",
    "生成子块数据集": "Generate sub-patch dataset",
    "中止": "Abort",
    "输出目录有时间戳": "Timestamp in out folder",
    "验证子块数据集与工具": "Validation and tools",
    "多框": "N-box",
    "单框": "1-box",
    "原图": "Source",
    "刷新标注": "Refresh labels",
    "反选": "Invert",
    "类别筛选": "Category filter",
    "全选": "Sel All",
    "删除未选中的类别": "Del non-checked",
    "导出数据集格式": "Export format",
    "导出": "Export",
    "文件": "File",
    "调试": "Debug",
    "工具": "Tools",
    "只在当前图像上生成多框数据集" : "Generate N-box sub dataset for current image",
    "显示指定的图像..." : "Show specified image number...",
    "删除未选中的标签" : "Delete non-checked tags",
    "锚框工具" : "Anchor-box tool",
    "保存配置" : "Save config",
    "配置另存为..." : "Save config as...",
    "打开配置" : "Open config",
    "自动打开上次配置" : "Auto open last config"

}

g_dctCHS = {
    "数据集化简分割工具" : "数据集化简分割工具",
    "子块数据集配置" : "子块数据集配置",
    "合并至少几个邻近物体" : "合并至少几个邻近物体",
    "生成数量" : "生成数量",
    "子块 H" : "子块 H",
    "子块 W" : "子块 W",
    "单物体面积占比范围" : "单物体面积占比范围",
    "物体区域最小占比" : "物体区域最小占比",
    "允许更密集" : "允许更密集",
    "只使用长宽比符合约束的物体" : "只使用长宽比符合约束的物体",
    "源数据集选择" : "源数据集选择",
    "子集" : "子集",
    "选择目录..." : "选择目录...",
    "类型" : "类型",
    "装载" : "装载",
    "自动装载" : "自动装载",
    "随机显示" : "随机显示",
    "导出标注" : "导出标注",
    "边框高/宽的范围" : "边框高/宽的范围",
    "每张图中边框个数的范围" : "每张图中边框个数的范围",
    "只读取符合约束的图" : "只读取符合约束的图",
    "生成子块数据集" : "生成子块数据集",
    "单框" : "单框",
    "多框" : "多框",
    "中止" : "中止",
    "输出目录有时间戳" : "输出目录有时间戳",
    "验证子块数据集与工具" : "验证子块数据集与工具",
    "原图" : "原图",
    "刷新标注" : "刷新标注",
    "反选" : "反选",
    "类别筛选" : "类别筛选",
    "全选" : "全选",
    "删除未选中的类别" : "删除未选中的类别",
    "导出数据集格式" : "导出数据集格式",
    "导出" : "导出",
    "文件" : "文件",
    "调试" : "调试",
    "工具" : "工具",
    "只在当前图像上生成多框数据集" : "只在当前图像上生成多框数据集",
    "显示指定的图像..." : "显示指定的图像...",
    "删除未选中的标签" : "删除未选中的标签",
    "锚框工具" : "锚框工具",
    "保存配置" : "保存配置",
    "配置另存为..." : "配置另存为...",
    "打开配置" : "打开配置",
    "自动打开上次配置" : "自动打开上次配置"    
}

g_dctLang = {
    'ENG' : g_dctENG,
    'CHS' : g_dctCHS
}