# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_ab_dlg_cfg_cluster.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Cfg_Cluster(object):
    def setupUi(self, Dialog_Cfg_Cluster):
        Dialog_Cfg_Cluster.setObjectName("Dialog_Cfg_Cluster")
        Dialog_Cfg_Cluster.resize(1275, 762)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Cfg_Cluster)
        self.buttonBox.setGeometry(QtCore.QRect(640, 30, 221, 32))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblClusters = QtWidgets.QLabel(Dialog_Cfg_Cluster)
        self.lblClusters.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblClusters.setFont(font)
        self.lblClusters.setObjectName("lblClusters")
        self.sldMaxClusters = QtWidgets.QSlider(Dialog_Cfg_Cluster)
        self.sldMaxClusters.setGeometry(QtCore.QRect(100, 30, 160, 22))
        self.sldMaxClusters.setMinimum(1)
        self.sldMaxClusters.setMaximum(30)
        self.sldMaxClusters.setPageStep(1)
        self.sldMaxClusters.setProperty("value", 5)
        self.sldMaxClusters.setOrientation(QtCore.Qt.Horizontal)
        self.sldMaxClusters.setObjectName("sldMaxClusters")
        self.fraAutoDecCluster = QtWidgets.QGroupBox(Dialog_Cfg_Cluster)
        self.fraAutoDecCluster.setEnabled(False)
        self.fraAutoDecCluster.setGeometry(QtCore.QRect(310, 20, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fraAutoDecCluster.setFont(font)
        self.fraAutoDecCluster.setCheckable(True)
        self.fraAutoDecCluster.setObjectName("fraAutoDecCluster")
        self.sldMaxClusters_2 = QtWidgets.QSlider(self.fraAutoDecCluster)
        self.sldMaxClusters_2.setGeometry(QtCore.QRect(80, 20, 181, 22))
        self.sldMaxClusters_2.setMaximum(10)
        self.sldMaxClusters_2.setPageStep(2)
        self.sldMaxClusters_2.setProperty("value", 5)
        self.sldMaxClusters_2.setOrientation(QtCore.Qt.Horizontal)
        self.sldMaxClusters_2.setObjectName("sldMaxClusters_2")
        self.label_2 = QtWidgets.QLabel(self.fraAutoDecCluster)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fraGraph = QtWidgets.QGroupBox(Dialog_Cfg_Cluster)
        self.fraGraph.setGeometry(QtCore.QRect(20, 90, 1241, 651))
        self.fraGraph.setObjectName("fraGraph")

        self.retranslateUi(Dialog_Cfg_Cluster)
        self.buttonBox.accepted.connect(Dialog_Cfg_Cluster.accept)
        self.buttonBox.rejected.connect(Dialog_Cfg_Cluster.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Cfg_Cluster)

    def retranslateUi(self, Dialog_Cfg_Cluster):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Cfg_Cluster.setWindowTitle(_translate("Dialog_Cfg_Cluster", "锚框聚类配置"))
        self.lblClusters.setText(_translate("Dialog_Cfg_Cluster", "最大群聚数=5"))
        self.fraAutoDecCluster.setTitle(_translate("Dialog_Cfg_Cluster", "自动减少聚类数"))
        self.label_2.setText(_translate("Dialog_Cfg_Cluster", "容差级别"))
        self.fraGraph.setTitle(_translate("Dialog_Cfg_Cluster", "GroupBox"))
